version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - ENVIRONMENT=development
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sec_filings
    tmpfs:
      - /var/lib/postgresql/data
    # For persistent data, replace tmpfs with a named volume

# To limit Docker Desktop disk image size, go to Docker Desktop > Settings > Resources > Advanced > Disk image size and set to 2GB.

volumes:
  postgres_data: 